//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ExcelAddIn3
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RSFinanceToolsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RSFinanceToolsEntities object using the connection string found in the 'RSFinanceToolsEntities' section of the application configuration file.
        /// </summary>
        public RSFinanceToolsEntities() : base("name=RSFinanceToolsEntities", "RSFinanceToolsEntities")
        {
            //this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RSFinanceToolsEntities object.
        /// </summary>
        public RSFinanceToolsEntities(string connectionString) : base(connectionString, "RSFinanceToolsEntities")
        {
            //this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RSFinanceToolsEntities object.
        /// </summary>
        public RSFinanceToolsEntities(EntityConnection connection) : base(connection, "RSFinanceToolsEntities")
        {
            //this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VIEW_DOC> VIEW_DOC
        {
            get
            {
                if ((_VIEW_DOC == null))
                {
                    _VIEW_DOC = base.CreateObjectSet<VIEW_DOC>("VIEW_DOC");
                }
                return _VIEW_DOC;
            }
        }
        private ObjectSet<VIEW_DOC> _VIEW_DOC;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FinTools_Settings> FinTools_Settings
        {
            get
            {
                if ((_FinTools_Settings == null))
                {
                    _FinTools_Settings = base.CreateObjectSet<FinTools_Settings>("FinTools_Settings");
                }
                return _FinTools_Settings;
            }
        }
        private ObjectSet<FinTools_Settings> _FinTools_Settings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VIEW_DOC EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVIEW_DOC(VIEW_DOC vIEW_DOC)
        {
            base.AddObject("VIEW_DOC", vIEW_DOC);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FinTools_Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFinTools_Settings(FinTools_Settings finTools_Settings)
        {
            base.AddObject("FinTools_Settings", finTools_Settings);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RSFinanceToolsModel", Name="FinTools_Settings")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FinTools_Settings : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FinTools_Settings object.
        /// </summary>
        /// <param name="ft_id">Initial value of the ft_id property.</param>
        /// <param name="ft_folder">Initial value of the ft_folder property.</param>
        public static FinTools_Settings CreateFinTools_Settings(global::System.Guid ft_id, global::System.String ft_folder)
        {
            FinTools_Settings finTools_Settings = new FinTools_Settings();
            finTools_Settings.ft_id = ft_id;
            finTools_Settings.ft_folder = ft_folder;
            return finTools_Settings;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ft_id
        {
            get
            {
                return _ft_id;
            }
            set
            {
                if (_ft_id != value)
                {
                    Onft_idChanging(value);
                    ReportPropertyChanging("ft_id");
                    _ft_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ft_id");
                    Onft_idChanged();
                }
            }
        }
        private global::System.Guid _ft_id;
        partial void Onft_idChanging(global::System.Guid value);
        partial void Onft_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ft_folder
        {
            get
            {
                return _ft_folder;
            }
            set
            {
                Onft_folderChanging(value);
                ReportPropertyChanging("ft_folder");
                _ft_folder = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ft_folder");
                Onft_folderChanged();
            }
        }
        private global::System.String _ft_folder;
        partial void Onft_folderChanging(global::System.String value);
        partial void Onft_folderChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RSFinanceToolsModel", Name="VIEW_DOC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VIEW_DOC : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VIEW_DOC object.
        /// </summary>
        /// <param name="vd_id">Initial value of the vd_id property.</param>
        /// <param name="vd_type">Initial value of the vd_type property.</param>
        /// <param name="vd_prefix">Initial value of the vd_prefix property.</param>
        /// <param name="vd_use_ref_as_name">Initial value of the vd_use_ref_as_name property.</param>
        public static VIEW_DOC CreateVIEW_DOC(global::System.Guid vd_id, global::System.String vd_type, global::System.String vd_prefix, global::System.Boolean vd_use_ref_as_name)
        {
            VIEW_DOC vIEW_DOC = new VIEW_DOC();
            vIEW_DOC.vd_id = vd_id;
            vIEW_DOC.vd_type = vd_type;
            vIEW_DOC.vd_prefix = vd_prefix;
            vIEW_DOC.vd_use_ref_as_name = vd_use_ref_as_name;
            return vIEW_DOC;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid vd_id
        {
            get
            {
                return _vd_id;
            }
            set
            {
                if (_vd_id != value)
                {
                    Onvd_idChanging(value);
                    ReportPropertyChanging("vd_id");
                    _vd_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("vd_id");
                    Onvd_idChanged();
                }
            }
        }
        private global::System.Guid _vd_id;
        partial void Onvd_idChanging(global::System.Guid value);
        partial void Onvd_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vd_type
        {
            get
            {
                return _vd_type;
            }
            set
            {
                Onvd_typeChanging(value);
                ReportPropertyChanging("vd_type");
                _vd_type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vd_type");
                Onvd_typeChanged();
            }
        }
        private global::System.String _vd_type;
        partial void Onvd_typeChanging(global::System.String value);
        partial void Onvd_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String vd_prefix
        {
            get
            {
                return _vd_prefix;
            }
            set
            {
                Onvd_prefixChanging(value);
                ReportPropertyChanging("vd_prefix");
                _vd_prefix = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("vd_prefix");
                Onvd_prefixChanged();
            }
        }
        private global::System.String _vd_prefix;
        partial void Onvd_prefixChanging(global::System.String value);
        partial void Onvd_prefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vd_folder
        {
            get
            {
                return _vd_folder;
            }
            set
            {
                Onvd_folderChanging(value);
                ReportPropertyChanging("vd_folder");
                _vd_folder = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vd_folder");
                Onvd_folderChanged();
            }
        }
        private global::System.String _vd_folder;
        partial void Onvd_folderChanging(global::System.String value);
        partial void Onvd_folderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean vd_use_ref_as_name
        {
            get
            {
                return _vd_use_ref_as_name;
            }
            set
            {
                Onvd_use_ref_as_nameChanging(value);
                ReportPropertyChanging("vd_use_ref_as_name");
                _vd_use_ref_as_name = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vd_use_ref_as_name");
                Onvd_use_ref_as_nameChanged();
            }
        }
        private global::System.Boolean _vd_use_ref_as_name;
        partial void Onvd_use_ref_as_nameChanging(global::System.Boolean value);
        partial void Onvd_use_ref_as_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vd_file
        {
            get
            {
                return _vd_file;
            }
            set
            {
                Onvd_fileChanging(value);
                ReportPropertyChanging("vd_file");
                _vd_file = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vd_file");
                Onvd_fileChanged();
            }
        }
        private global::System.String _vd_file;
        partial void Onvd_fileChanging(global::System.String value);
        partial void Onvd_fileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vd_filetype
        {
            get
            {
                return _vd_filetype;
            }
            set
            {
                Onvd_filetypeChanging(value);
                ReportPropertyChanging("vd_filetype");
                _vd_filetype = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vd_filetype");
                Onvd_filetypeChanged();
            }
        }
        private global::System.String _vd_filetype;
        partial void Onvd_filetypeChanging(global::System.String value);
        partial void Onvd_filetypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vd_macro01
        {
            get
            {
                return _vd_macro01;
            }
            set
            {
                Onvd_macro01Changing(value);
                ReportPropertyChanging("vd_macro01");
                _vd_macro01 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vd_macro01");
                Onvd_macro01Changed();
            }
        }
        private global::System.String _vd_macro01;
        partial void Onvd_macro01Changing(global::System.String value);
        partial void Onvd_macro01Changed();

        #endregion
    
    }

    #endregion
    
}
